In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.preprocessing import MinMaxScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix


In [14]:
df=pd.read_csv('Crop_recommendation.csv')
df.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice


In [15]:
df.shape

(2200, 8)

In [16]:
df.value_counts()

N    P    K    temperature  humidity   ph        rainfall    label      
0    5    36   24.351938    90.886124  6.152907  105.529185  pomegranate    1
69   60   54   36.322681    93.061344  6.989927  141.173693  papaya         1
     37   42   23.058049    83.370118  7.073454  251.055000  rice           1
     46   41   23.641248    80.285979  5.012140  263.110330  rice           1
     47   40   25.371227    76.240367  6.130136  183.827079  jute           1
                                                                           ..
26   126  195  21.413638    92.991245  5.878569  118.397907  apple          1
     122  202  22.445170    94.737635  5.617227  107.184327  apple          1
     121  201  22.191094    90.025751  6.162034  112.312663  apple          1
     80   83   17.084985    16.145658  7.528600  71.310073   chickpea       1
140  45   15   25.530827    80.046628  5.801048  99.395572   cotton         1
Name: count, Length: 2200, dtype: int64

In [17]:
len(df['label'].value_counts())

22

In [19]:
print(len(df['label'].values))

2200


In [20]:
encoder=LabelEncoder()
df['label']=encoder.fit_transform(df['label'])
df.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,90,42,43,20.879744,82.002744,6.502985,202.935536,20
1,85,58,41,21.770462,80.319644,7.038096,226.655537,20
2,60,55,44,23.004459,82.320763,7.840207,263.964248,20
3,74,35,40,26.491096,80.158363,6.980401,242.864034,20
4,78,42,42,20.130175,81.604873,7.628473,262.717340,20


In [21]:
df['label'].values

array([20, 20, 20, ...,  5,  5,  5], shape=(2200,))

In [26]:
# scaling normalization
numeric_cols=['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

scaler=MinMaxScaler()
df[numeric_cols]=scaler.fit_transform(df[numeric_cols])
df.head()

,N,P,K,temperature,humidity,ph,rainfall,label
0,0.642857,0.264286,0.190,0.345886,0.790267,0.466264,0.656458,20
1,0.607143,0.378571,0.180,0.371445,0.770633,0.549480,0.741675,20
2,0.428571,0.357143,0.195,0.406854,0.793977,0.674219,0.875710,20
3,0.528571,0.214286,0.175,0.506901,0.768751,0.540508,0.799905,20
4,0.557143,0.264286,0.185,0.324378,0.785626,0.641291,0.871231,20


In [25]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [27]:
#train test split
X=df.drop('label', axis=1)
y=df['label']

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
# training testing multiple classifier

models={
    "lg":LogisticRegression(),
    "RFC":RandomForestClassifier(),
    "GBC":GradientBoostingClassifier()
}
#for name, model in models.items():
 #   model.fit(X_train,y_train)
  #  y_pred=model.predict(X_test)

   # print("name", name)
    #print('confusion_matric', confusion_matrix(y_test,y_pred))
    #print('report : \n', classification_report(y_test,y_pred))

for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

Model: lg
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        21
           2       0.89      0.85      0.87        20
           3       1.00      1.00      1.00        26
           4       1.00      1.00      1.00        27
           5       0.94      1.00      0.97        17
           6       0.94      1.00      0.97        17
           7       1.00      1.00      1.00        14
           8       0.84      0.70      0.76        23
           9       0.91      1.00      0.95        20
          10       0.69      1.00      0.81        11
          11       1.00      0.95      0.98        21
          12       0.66      1.00      0.79        19
          13       1.00      0.54      0.70        24
          14       0.86      1.00      0.93        19
          15       1.00      1.00      1.00        17
          16       1.00      1.00      1.00    

In [36]:
# selecting best model
model_gbc=GradientBoostingClassifier()
model_gbc.fit(X_train, y_train)
y_pred=model_gbc.predict(X_test)

In [38]:
print("confusion matrix \n:", confusion_matrix(y_test,y_pred))
print("classification report\n:", classification_report(y_test,y_pred))

confusion matrix 
: [[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 

In [42]:
import pickle
pickle.dump(encoder,open("encoder.pkl", 'wb'))
pickle.dump(model_gbc, open("model_gbc.pkl",'wb'))
pickle.dump(scaler, open("scaler.pkl",'wb'))

In [45]:
# inference (prediction on new data)

encoder=pickle.load(open("encoder.pkl", 'rb'))
model_gbc=pickle.load(open("model_gbc.pkl",'rb'))
scaler=pickle.load(open("scaler.pkl",'rb'))

In [49]:
def predict_crop(N,P,K,temperature,humidity,ph,rainfall):
    #create dataframe form input columns
    input_df=pd.DataFrame([[N,P,K,temperature,humidity,ph,rainfall]],
                          columns=['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'])

    #scale the data
    input_scaled=scaler.transform(input_df)

    #predict and decode
    prediction_encoded=model_gbc.predict(input_scaled)
    prediction=encoder.inverse_transform(prediction_encoded)

    return prediction[0]

In [51]:
result=predict_crop(90,40,40,25.0,80.0,6.5,100.0)
print("Recommended Crop", result)

Recommended Crop jute


C:\Users\Tejas Nikam\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


In [52]:
import sklearn 
print(sklearn.__version__)

1.7.2
